import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/homepage/header";
import HeaderClient from "@/components/HeaderClient";
import Footer from "@/components/footer";
import { Toaster } from "sonner";
import WhatsAppButton from "../components/WhatsAppButton";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Events2go",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderClient/>
        {children}
        <WhatsAppButton/>
        <Footer/>
        <Toaster richColors position="bottom-right" />
      </body>
    </html>
  );
}
